language: c
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
script: make ; make test

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev uuid-dev libuuid1 xsltproc docbook-xsl

